% build_epri_evcharger_posseq_model.m
% Build EPRI EVCharger positive-sequence Simulink model (PDF-calibrated).
% PDF parameters from Appendix A of EVCharger_Model_Specifications_2023.
%
% Key improvements over prior qualitative model:
%   - nPB=1 (Fraction B constant-current during sag, P=P0*V)
%   - All cessation/reconnect timers from PDF Appendix A
%   - Washout block (Kvp*Tvp*s/(Tvp*s+1)) in each fraction
%   - Numerical stability filter 1/(Tnum*s+1) in each fraction
%   - ipmax=2.0 (allows constant power at V=0.5 pu)
%   - vrX=0.6 (reconnect threshold from PDF, not 0.90 assumed)
%   - Tstop=20s to capture full Fraction A recovery

if ~exist('P_A_kW','var')
    run(fullfile(fileparts(mfilename('fullpath')), 'epri_ev_params_init.m'));
end

mdlName = 'epri_evcharger_posseq_dynamic_r2024b';
mdlPath = fullfile(project_root,'model',[mdlName '.slx']);

if bdIsLoaded(mdlName), close_system(mdlName,0); end
if exist(mdlPath,'file'), delete(mdlPath); end

new_system(mdlName);
open_system(mdlName);
set_param(mdlName,'Solver','FixedStepDiscrete','FixedStep',num2str(Ts), ...
    'StopTime',num2str(Tstop), ...
    'SaveTime','on','TimeSaveName','tout', ...
    'SaveOutput','off', ...
    'SignalLogging','on','SignalLoggingName','logsout');
set_param(mdlName,'Location',[20 20 1500 800]);

%% Layout constants
W=160; H=70;
c1=30; c2=230; c3=430; c4=630; c5=830; c6=1030; c7=1250;
r1=40; r2=200;

%% ---- Helper: set MATLAB Function code ----
function set_fcn_code(mdlName, blk_path, code)
    rt = sfroot;
    em = find(rt,'-isa','Stateflow.EMChart','Path',blk_path);
    if isempty(em), error('EMChart not found: %s', blk_path); end
    em.Script = code;
end

%% ============================================================
%% 1. Terminal_Voltage_Playback
%% ============================================================
ss1 = [mdlName '/Terminal_Voltage_Playback'];
add_block('built-in/Subsystem',ss1,'Position',[c1 r1 c1+W r1+H]);

add_block('built-in/Inport', [ss1 '/t'],    'Position',[20 40 50 60],'Port','1');
add_block('built-in/Outport',[ss1 '/Vt_pu'],'Position',[420 30 450 50],'Port','1');
add_block('built-in/Outport',[ss1 '/Vmea'], 'Position',[420 70 450 90],'Port','2');

% gen_vt: generates Vt_pu step from t
add_block('simulink/User-Defined Functions/MATLAB Function',[ss1 '/gen_vt'], ...
    'Position',[90 30 210 70]);
vt_code = sprintf('function Vt = gen_vt(t)\n%%%%#codegen\nif t >= %.6f && t < %.6f\n    Vt = %.4f;\nelse\n    Vt = 1.0;\nend\n', ...
    sag_start, sag_end, sag_depth);
set_fcn_code(mdlName, [ss1 '/gen_vt'], vt_code);

% Discrete first-order filter for Vmea: alpha = Ts/Tr
alpha_r = Ts / Tr;
add_block('simulink/Math Operations/Sum',       [ss1 '/sum_vmea'],'Position',[255 60 285 90],'Inputs','+-');
add_block('simulink/Discrete/Unit Delay',       [ss1 '/ud_vmea'], 'Position',[315 62 365 88],'SampleTime',num2str(Ts),'X0','1.0');
add_block('simulink/Math Operations/Gain',      [ss1 '/g_alpha'], 'Position',[230 35 252 55],'Gain',num2str(alpha_r));
add_block('simulink/Math Operations/Sum',       [ss1 '/sum_vf'],  'Position',[293 30 323 52],'Inputs','++');

add_line(ss1,'t/1','gen_vt/1','autorouting','on');
add_line(ss1,'gen_vt/1','sum_vmea/1','autorouting','on');
add_line(ss1,'ud_vmea/1','sum_vmea/2','autorouting','on');
add_line(ss1,'sum_vmea/1','g_alpha/1','autorouting','on');
add_line(ss1,'g_alpha/1','sum_vf/1','autorouting','on');
add_line(ss1,'ud_vmea/1','sum_vf/2','autorouting','on');
add_line(ss1,'sum_vf/1','ud_vmea/1','autorouting','on');
add_line(ss1,'gen_vt/1','Vt_pu/1','autorouting','on');
add_line(ss1,'sum_vf/1','Vmea/1','autorouting','on');

%% ============================================================
%% MATLAB Function code generators (PDF-calibrated)
%% ============================================================

function code = frac_AC_code(fname, P_rated, vc, tc_s, tdelay_s, vr, tr, tramp, Ts_val)
% Fractions A and C: nP=0 (constant power). Cease on UV, reconnect + ramp.
% Includes: washout (Kvp/Tvp), numerical filter (Tnum=4*Ts), ipmax=2.0
tc_tot = tc_s + tdelay_s;
code = sprintf([ ...
'function [P_fr_kW,Q_fr_kvar,IP_pu,IQ_pu,cessation,FR_not_ceased] = %s(t,Vt_pu,Vmea)\n' ...
'%%%%#codegen\n' ...
'persistent state tuv trec Iramp Pfilt Vprev Wout\n' ...
'if isempty(state)\n' ...
'  state=int8(0);tuv=double(0);trec=double(0);Iramp=double(1);\n' ...
'  Pfilt=double(%.6f);Vprev=double(1);Wout=double(0);\n' ...
'end\n' ...
'PR=double(%.6f);vc=double(%.4f);tc=double(%.6f);vr=double(%.4f);tr=double(%.4f);\n' ...
'tramp=double(%.4f);Kvp=double(0.2);Tvp=double(0.02);ipm=double(2.0);\n' ...
'Ts=double(%.8f);Tnum=double(%.8f);\n' ...
'Wout=(Tvp/(Tvp+Ts))*Wout+Kvp*(Vmea-Vprev); Vprev=Vmea;\n' ...
'switch state\n' ...
' case int8(0)\n' ...
'  Iramp=double(1);\n' ...
'  if Vmea<vc; tuv=tuv+Ts; if tuv>=tc; state=int8(2);tuv=double(0);trec=double(0);Iramp=double(0); end\n' ...
'  else; tuv=double(0); end\n' ...
' case int8(2)\n' ...
'  Iramp=double(0);\n' ...
'  if Vmea>=vr; trec=trec+Ts; if trec>=tr; state=int8(3); end\n' ...
'  else; trec=double(0); end\n' ...
' case int8(3)\n' ...
'  Iramp=Iramp+Ts/tramp;\n' ...
'  if Iramp>=double(1); Iramp=double(1); state=int8(0); end\n' ...
'  if Vmea<vc; state=int8(2); Iramp=double(0); trec=double(0); end\n' ...
'end\n' ...
'V_s=max(Vt_pu,double(0.05));\n' ...
'IP_raw=Iramp/V_s;\n' ...           % nP=0: constant power IP=P/V
'IP_pu=min(max(IP_raw,double(-2)),ipm);\n' ...
'IQ_pu=double(0);\n' ...
'cessation=double(state~=int8(0)); FR_not_ceased=double(state==int8(0));\n' ...
'Praw=V_s*IP_pu*PR+Wout*PR;\n' ...
'Pfilt=Pfilt+(Ts/Tnum)*(Praw-Pfilt);\n' ...
'P_fr_kW=double(max(Pfilt,0)); Q_fr_kvar=double(0);\n' ...
'end\n'], ...
fname, P_rated, P_rated, vc, tc_tot, vr, tr, tramp, Ts_val, 4*Ts_val);
end

function code = frac_B_code(fname, P_rated, vc, tc_s, tdelay_s, vr, tr, tramp, Ts_val)
% Fraction B: nP=1 (constant current). During sag P=P0*V before ceasing.
tc_tot = tc_s + tdelay_s;
code = sprintf([ ...
'function [P_fr_kW,Q_fr_kvar,IP_pu,IQ_pu,cessation,FR_not_ceased] = %s(t,Vt_pu,Vmea)\n' ...
'%%%%#codegen\n' ...
'persistent state tuv trec Iramp Pfilt Vprev Wout\n' ...
'if isempty(state)\n' ...
'  state=int8(0);tuv=double(0);trec=double(0);Iramp=double(1);\n' ...
'  Pfilt=double(%.6f);Vprev=double(1);Wout=double(0);\n' ...
'end\n' ...
'PR=double(%.6f);vc=double(%.4f);tc=double(%.6f);vr=double(%.4f);tr=double(%.4f);\n' ...
'tramp=double(%.4f);Kvp=double(0.2);Tvp=double(0.02);ipm=double(2.0);\n' ...
'Ts=double(%.8f);Tnum=double(%.8f);\n' ...
'Wout=(Tvp/(Tvp+Ts))*Wout+Kvp*(Vmea-Vprev); Vprev=Vmea;\n' ...
'switch state\n' ...
' case int8(0)\n' ...
'  if Vmea>=vc\n' ...
'    Iramp=double(1); tuv=double(0);\n' ...
'  else\n' ...
'    Iramp=double(max(Vmea,0))/vc;\n' ...  % nP=1: proportional to V/vc during sag
'    tuv=tuv+Ts; if tuv>=tc; state=int8(2);tuv=double(0);trec=double(0);Iramp=double(0); end\n' ...
'  end\n' ...
' case int8(2)\n' ...
'  Iramp=double(0);\n' ...
'  if Vmea>=vr; trec=trec+Ts; if trec>=tr; state=int8(3); end\n' ...
'  else; trec=double(0); end\n' ...
' case int8(3)\n' ...
'  Iramp=Iramp+Ts/tramp;\n' ...
'  if Iramp>=double(1); Iramp=double(1); state=int8(0); end\n' ...
'  if Vmea<vc; state=int8(2); Iramp=double(0); trec=double(0); end\n' ...
'end\n' ...
'V_s=max(Vt_pu,double(0.05));\n' ...
'IP_pu=min(max(Iramp,double(-2)),double(2));\n' ...  % nP=1: IP = Iramp (constant current)
'IQ_pu=double(0);\n' ...
'cessation=double(state~=int8(0)); FR_not_ceased=double(state==int8(0));\n' ...
'Praw=V_s*IP_pu*PR+Wout*PR;\n' ...
'Pfilt=Pfilt+(Ts/Tnum)*(Praw-Pfilt);\n' ...
'P_fr_kW=double(max(Pfilt,0)); Q_fr_kvar=double(0);\n' ...
'end\n'], ...
fname, P_rated, P_rated, vc, tc_tot, vr, tr, tramp, Ts_val, 4*Ts_val);
end

function code = frac_D_code(fname, P_rated, Ts_val)
% Fraction D: nP=0 constant power, no cessation. Washout + numerical filter.
code = sprintf([ ...
'function [P_fr_kW,Q_fr_kvar,IP_pu,IQ_pu] = %s(t,Vt_pu,Vmea)\n' ...
'%%%%#codegen\n' ...
'persistent Pfilt Vprev Wout\n' ...
'if isempty(Pfilt); Pfilt=double(%.6f); Vprev=double(1); Wout=double(0); end\n' ...
'PR=double(%.6f); Kvp=double(0.2); Tvp=double(0.02); ipm=double(2.0);\n' ...
'Ts=double(%.8f); Tnum=double(%.8f);\n' ...
'Wout=(Tvp/(Tvp+Ts))*Wout+Kvp*(Vmea-Vprev); Vprev=Vmea;\n' ...
'V_s=max(Vt_pu,double(0.05));\n' ...
'IP_raw=double(1)/V_s;\n' ...   % nP=0: constant power
'IP_pu=min(max(IP_raw,double(-2)),ipm);\n' ...
'IQ_pu=double(0);\n' ...
'Praw=V_s*IP_pu*PR+Wout*PR;\n' ...
'Pfilt=Pfilt+(Ts/Tnum)*(Praw-Pfilt);\n' ...
'P_fr_kW=double(max(Pfilt,0)); Q_fr_kvar=double(0);\n' ...
'end\n'], fname, P_rated, P_rated, Ts_val, 4*Ts_val);
end

%% ============================================================
%% Build fraction subsystem helper
%% ============================================================
function build_frac_ss(mdlName, ss_path, fcn_name, fcn_code, out_pref, n_outs, pos)
add_block('built-in/Subsystem',ss_path,'Position',pos);
add_block('built-in/Inport',[ss_path '/t'],     'Position',[20 30 50 50],'Port','1');
add_block('built-in/Inport',[ss_path '/Vt_pu'], 'Position',[20 70 50 90],'Port','2');
add_block('built-in/Inport',[ss_path '/Vmea'],  'Position',[20 110 50 130],'Port','3');

if n_outs == 6
    out6 = {[out_pref '_kW'],[out_pref 'r_kvar'], ...
            ['IP' out_pref '_pu'],['IQ' out_pref '_pu'], ...
            ['cessation_' out_pref(end)],['FR' out_pref(end)]};
else
    out6 = {[out_pref '_kW'],[out_pref 'r_kvar'], ...
            ['IP' out_pref '_pu'],['IQ' out_pref '_pu']};
end
for k = 1:n_outs
    yp = 20+(k-1)*28;
    add_block('built-in/Outport',[ss_path '/' out6{k}], ...
        'Position',[420 yp 450 yp+18],'Port',num2str(k));
end

add_block('simulink/User-Defined Functions/MATLAB Function', ...
    [ss_path '/' fcn_name],'Position',[100 30 360 30+n_outs*28]);

rt = sfroot;
em = find(rt,'-isa','Stateflow.EMChart','Path',[ss_path '/' fcn_name]);
if isempty(em), error('EMChart not found: %s/%s',ss_path,fcn_name); end
em.Script = fcn_code;

add_line(ss_path,'t/1',    [fcn_name '/1'],'autorouting','on');
add_line(ss_path,'Vt_pu/1',[fcn_name '/2'],'autorouting','on');
add_line(ss_path,'Vmea/1', [fcn_name '/3'],'autorouting','on');
for k = 1:n_outs
    add_line(ss_path,[fcn_name '/' num2str(k)],[out6{k} '/1'],'autorouting','on');
end
end

%% ============================================================
%% 2-5. Build fraction subsystems
%% ============================================================
code_A = frac_AC_code('EVCharger_Fraction_A', P_A_kW, vcA, tcA, tdelayA, vrA, trA, trampA, Ts);
build_frac_ss(mdlName,[mdlName '/EVCharger_Fraction_A'], ...
    'EVCharger_Fraction_A',code_A,'PfrA',6,[c2 r1 c2+W r1+H]);

code_B = frac_B_code('EVCharger_Fraction_B', P_B_kW, vcB, tcB, tdelayB, vrB, trB, trampB, Ts);
build_frac_ss(mdlName,[mdlName '/EVCharger_Fraction_B'], ...
    'EVCharger_Fraction_B',code_B,'PfrB',6,[c3 r1 c3+W r1+H]);

code_C = frac_AC_code('EVCharger_Fraction_C', P_C_kW, vcC, tcC, tdelayC, vrC, trC, trampC, Ts);
build_frac_ss(mdlName,[mdlName '/EVCharger_Fraction_C'], ...
    'EVCharger_Fraction_C',code_C,'PfrC',6,[c4 r1 c4+W r1+H]);

code_D = frac_D_code('EVCharger_Fraction_D', P_D_kW, Ts);
build_frac_ss(mdlName,[mdlName '/EVCharger_Fraction_D'], ...
    'EVCharger_Fraction_D',code_D,'PfrD',4,[c5 r1 c5+W r1+H]);

%% ============================================================
%% 6. Cumulative_Output
%% ============================================================
ss6 = [mdlName '/Cumulative_Output'];
add_block('built-in/Subsystem',ss6,'Position',[c6 r1 c6+W r1+H]);
nm8 = {'PfrA','PfrB','PfrC','PfrD','QfrA','QfrB','QfrC','QfrD'};
for k=1:8
    add_block('built-in/Inport',[ss6 '/' nm8{k}], ...
        'Position',[20 15+(k-1)*30 55 33+(k-1)*30],'Port',num2str(k));
end
add_block('built-in/Outport',[ss6 '/Pout'],'Position',[350 40 380 60],'Port','1');
add_block('built-in/Outport',[ss6 '/Qout'],'Position',[350 80 380 100],'Port','2');
add_block('simulink/Math Operations/Sum',[ss6 '/sum_P'],'Position',[220 35 255 55],'Inputs','++++');
add_block('simulink/Math Operations/Sum',[ss6 '/sum_Q'],'Position',[220 75 255 95],'Inputs','++++');
for k=1:4
    add_line(ss6,[nm8{k} '/1'],  ['sum_P/' num2str(k)],'autorouting','on');
    add_line(ss6,[nm8{k+4} '/1'],['sum_Q/' num2str(k)],'autorouting','on');
end
add_line(ss6,'sum_P/1','Pout/1','autorouting','on');
add_line(ss6,'sum_Q/1','Qout/1','autorouting','on');

%% ============================================================
%% 7. Measurements
%% ============================================================
ss7 = [mdlName '/Measurements'];
add_block('built-in/Subsystem',ss7,'Position',[c7 r1 c7+130 r1+310]);
meas = {'tout_sig','Vt_pu','Vmea','Pout','Qout', ...
    'PfrA','QfrA','PfrB','QfrB','PfrC','QfrC','PfrD','QfrD', ...
    'IPfA','IQfA','IPfB','IQfB','IPfC','IQfC','IPfD','IQfD', ...
    'FRA','FRB','FRC','cessation_A','cessation_B','cessation_C'};
ws_nms = meas; ws_nms{1} = 'tout_ws';
for k=1:numel(meas)
    yp = 15+(k-1)*28;
    add_block('built-in/Inport',[ss7 '/' meas{k}], ...
        'Position',[15 yp 55 yp+18],'Port',num2str(k));
    add_block('simulink/Sinks/To Workspace',[ss7 '/tw_' meas{k}], ...
        'Position',[75 yp 225 yp+18], ...
        'VariableName',ws_nms{k},'SampleTime','-1','SaveFormat','Array');
    add_line(ss7,[meas{k} '/1'],['tw_' meas{k} '/1'],'autorouting','on');
end

%% ============================================================
%% Top-level connections
%% ============================================================
add_block('simulink/Sources/Clock',[mdlName '/Clk'], ...
    'Position',[20 r2+20 55 r2+40]);
add_line(mdlName,'Clk/1','Terminal_Voltage_Playback/1','autorouting','on');

frac_ss = {'EVCharger_Fraction_A','EVCharger_Fraction_B', ...
           'EVCharger_Fraction_C','EVCharger_Fraction_D'};
for k=1:4
    add_line(mdlName,'Clk/1',[frac_ss{k} '/1'],'autorouting','on');
    add_line(mdlName,'Terminal_Voltage_Playback/1',[frac_ss{k} '/2'],'autorouting','on');
    add_line(mdlName,'Terminal_Voltage_Playback/2',[frac_ss{k} '/3'],'autorouting','on');
end

add_line(mdlName,'EVCharger_Fraction_A/1','Cumulative_Output/1','autorouting','on');
add_line(mdlName,'EVCharger_Fraction_B/1','Cumulative_Output/2','autorouting','on');
add_line(mdlName,'EVCharger_Fraction_C/1','Cumulative_Output/3','autorouting','on');
add_line(mdlName,'EVCharger_Fraction_D/1','Cumulative_Output/4','autorouting','on');
add_line(mdlName,'EVCharger_Fraction_A/2','Cumulative_Output/5','autorouting','on');
add_line(mdlName,'EVCharger_Fraction_B/2','Cumulative_Output/6','autorouting','on');
add_line(mdlName,'EVCharger_Fraction_C/2','Cumulative_Output/7','autorouting','on');
add_line(mdlName,'EVCharger_Fraction_D/2','Cumulative_Output/8','autorouting','on');

meas_src = { ...
    'Clk/1', ...
    'Terminal_Voltage_Playback/1','Terminal_Voltage_Playback/2', ...
    'Cumulative_Output/1','Cumulative_Output/2', ...
    'EVCharger_Fraction_A/1','EVCharger_Fraction_A/2', ...
    'EVCharger_Fraction_B/1','EVCharger_Fraction_B/2', ...
    'EVCharger_Fraction_C/1','EVCharger_Fraction_C/2', ...
    'EVCharger_Fraction_D/1','EVCharger_Fraction_D/2', ...
    'EVCharger_Fraction_A/3','EVCharger_Fraction_A/4', ...
    'EVCharger_Fraction_B/3','EVCharger_Fraction_B/4', ...
    'EVCharger_Fraction_C/3','EVCharger_Fraction_C/4', ...
    'EVCharger_Fraction_D/3','EVCharger_Fraction_D/4', ...
    'EVCharger_Fraction_A/6','EVCharger_Fraction_B/6','EVCharger_Fraction_C/6', ...
    'EVCharger_Fraction_A/5','EVCharger_Fraction_B/5','EVCharger_Fraction_C/5', ...
};
for k=1:numel(meas_src)
    add_line(mdlName,meas_src{k},sprintf('Measurements/%d',k),'autorouting','on');
end

%% Save: primary name + timing-corrected copy (do NOT overwrite verified baseline)
save_system(mdlName, mdlPath);

timing_path = fullfile(project_root,'model', ...
    'epri_evcharger_posseq_epri_timing_corrected_r2024b.slx');
save_system(mdlName, timing_path);

fprintf('Model saved:          %s\n', mdlPath);
fprintf('Timing-corrected copy: %s\n', timing_path);
fprintf('build_epri_evcharger_posseq_model (timing-corrected): COMPLETE\n');
